### ISSUE TITLE
using the listener

### ISSUE THREAD

**Issue by Bierseppi** [open-homeautomation/pknx#12]
Hello, 
i have following problem:
I don't understand how to use the listener i can register.
`def register_listeners(self,knx):
        file = open("data.csv")
        for line in file:
            adress=line.split(";")
            knx.register_listener(knxcore.parse_group_address(adress[0]),self.listener())

    def listener(self,adress,data):
        pass`
I describe now the way i understand this: 
I can register a listener witch listens is a new message is here from an registered adress. Now the method listener will get started. But get the data transfered into the method listener? 
can i now access the data in the listener method?

I hope you understand my issue.

Best regards

Max

**Comment by hifiberry** [comment]
The listener has 2 arguments: address and data. 
These arguments will be populated. So, you only have to use these arguments. address is the KNX address (as an integer) and data the data received (this is a list of bytes).

**Comment by open-homeautomation** [comment]
The listener has 2 arguments: address and data. 
These arguments will be populated. So, you only have to use these arguments. address is the KNX address (as an integer) and data the data received (this is a list of bytes).

**Comment by Bierseppi** [comment]
okay but the listener method is a self written method?

**Comment by open-homeautomation** [comment]
Yes, the listener is a method you you to write.
Check out this example:
https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/knx.py#L129-L141

**Comment by Bierseppi** [comment]
greate thank you ! Vielen Dank
