### ISSUE TITLE
Feature: Implementing Reconnection on the same Channel Id 

### ISSUE THREAD

**Issue by daBONDi** [open-homeautomation/pknx#14]
We need to Implement a Reconnection Thingy with the same channel id
maybe a file with a timestamp and ip/ports/ChannelId to Impelement Reconnecting.

or only safe the Channel Id, and after Reload, call a Disconnect with the Channel Id on the Tunnel GW, and start a new Connection, so there is nothing open on the tunnel device.

**Comment by open-homeautomation** [comment]
Why do we need this? The existing connection should be closed on shutdown.

**Comment by daBONDi** [comment]
Yeah the Probleme is with should be :-)

Got often the Problem when i want to develop something for hass the tunnel connection stay open because the disconnect not getting called when i stop the debugging session and the threads stops.

And after that 5 times i get blocked by the timeout on the Gateway.

How you do the debugging with hass? Prbly i do it wrong, any hints for me?

**Comment by open-homeautomation** [comment]
I have devices regularly posting messages on the KNX bus. If the IP gateway receives a message, but the connection isn't there anymore, it automatically closes the connection.

For your case, you do not need a reconnect feature, but more a cleanup. I'm not sure what would be the best way to implement this.

**Comment by open-homeautomation** [comment]
@daBONDi Is this still needed?
